### PR TITLE
fix!: Remove `setTimeout` from request handling middleware

### PR DESCRIPTION
**Pull request by sarpik**
Setting the delay to a fixed number is okay, but setting it to `0`
is better - it still ensures that the code runs right once we want it
without any additional delay.

I've tested this & it works just fine.

This is compatible with #33 and #31!

Edit: BREAKING CHANGE

Signed-off-by: Kipras Melnikovas <kipras@kipras.org>

### CODE REVIEW

**Comment by mpashkovskiy** [comment]
This delay is used to make sure express-oas-generator middleware is placed at the very end of the middlewares chain and will be able to process all the requests/responses. If we place middleware in front of any others we won't be ale to process request and responses properly. Here is example from server.js

```javascript
// Example of using the module

const express = require('express');
const bodyParser = require('body-parser');
const generator = require('./index.js');
const _ = require('lodash');
const zlib = require('zlib');

const app = express();
generator.init(app, function (spec) {
  _.set(spec, 'paths["/foo/{name}"].get.parameters[0].description', 'description of a parameter');
  return spec;
}, './test_spec.json');

app.use(bodyParser.json({}));
...

app.use(router);
app.set('port', 8080);
app.listen(app.get('port'));
```

Here our middleware is placed before `app.use(bodyParser.json({}));` thus when we process request/responses we get body as a string but not as a json and won't be able to generate proper schema for body.

**Comment by sarpik** [comment]
Thank you for the info, I'll take a deeper look to see if there's anything else I can do here.

**Comment by sarpik** [comment]
Interesting. Isn't this solution possibly error-prone?
Say, for example, someone uses `expressOasGenerator.init(app)`, then starts doing something else which takes more than the harcoded setTimeout of `1000` ms and thus the middleware is not placed exactly at the end?

I've tried

1. completely removing the `setTimeout` from the middleware to handle requests (https://github.com/sarpik/express-oas-generator/blob/1ab0f848ff3cc69afcfef2440c91b41a7d24de8f/index.js#L173-L188)
2. using the `expressOasGenerator.init(app)` on the app's listening callback:

```ts
const server = app.listen(PORT, async () => {
	console.log(`~ Server listening on PORT \`${PORT}\` @ NODE_ENV \`${process.env.NODE_ENV}\``);
	expressOasGenerator.init(app);
});
```

doesn't this seem like a better solution? We'd need to explicitly state that you need to use the `expressOasGenerator.init(app)` AFTER the app is listening, so, inside it's callback.

Also, this causes problems for me because if I want to start the server & then generate the docs, I cannot do it instantly because there's an asynchronous timeout. This would fix the problem too.

---

If you'd want to merge, I should update this to remove the `setTimeout` all together, because there's a difference.

**Comment by sarpik** [comment]
Lmao, I just found out why I wasn't able to generate the api docs (specifically, the responses) for over a week.

It's because you're supposed to put the `expressOasGenerator.init(app)` as soon as you create the express app (`const app = express()`).

I completely forgot this step because I thought that this PR could solve the `setTimeout` issue and you'd just have to place the `generator.init(app)` in the end, instead of the beginning. Nope.

This also makes this PR obsolete - since you're supposed to put the generator as soon as you init the app, you cannot remove the *hacky* `setTimeout`, since it has to be at the placed at the end.

If I have more time in the future, I'll try my best to look this up more in depth and possibly find a way to make this better:D

---

I'm interested as to why @mpashkovskiy chose this design?
https://github.com/mpashkovskiy/express-oas-generator/blob/master/index.js#L145-L192

As far as I understand, the `request` handler has to be placed as the first one, since there's no `setTimeout` for it, and the `response` handler has to be placed the last, since it has the `setTimeout`, right?

Is this how express works or are there some limitations or something of that nature, that makes us place the request handler as the very first one and the response handler as the very last one?

**Comment by mpashkovskiy** [comment]
First of the all, you are right that using one second as a timeout is error-prone. Indeed there could be some heavylifing initialization that takes more than a second and in those cases requests processing middleware wouldn't be the last one. True that it is possible to drop setTimeout and implement extra method in the module and do something like:

```
app.listen(PORT, () => {
	expressOasGenerator.injectRequestMiddleware(app);
});
```

But to simplify usage of the module I decided to avoid any extra calls of the module.

Answering to the second question: "Why do we place response processing middleware as the very first one?". The reason that we have to override response `write` and `end` methods in each and every request processing chain before any router/middleware start to use it. Thus we can get full response headers and body.

**Comment by sarpik** [comment]
That's interesting!

I think it'd be worth it to allow power users to have this functionality available to them.

For example, this would allow me to run tests instantly after starting the server without setting an arbitrary delay for the response handling middleware to take effect.
And this would get rid of the possible errors.

We can still keep the simple `init` which does both, but I think it'd be useful to let users know how this works and I think that nobody would mind adding 2 lines of code instead of one.

I can make a PR, this seems pretty simple to do now that I know the reasoning.
I think we can do this before 2.0 (https://github.com/mpashkovskiy/express-oas-generator/issues/35), since it'd just be a feature.

Also, I'll try looking into express's source code to see if we can somehow change the order of the middleware's, but I don't think that will be possible:D

**Comment by mpashkovskiy** [comment]
@sarpik shouldn't we discard this PR?

**Comment by sarpik** [comment]
@mpashkovskiy yep. This is no longer needed since #39 is now available, and the default `setTimeout` is actually needed.

**Pull request closed without merging**
