### PR TITLE
Create typescript support: Declarations file (`index.d.ts`), `tsconfig.json` & friends

### PR DESCRIPTION
**Pull request by sarpik**
I've created support for typescript types.

They're available for both us, the library owners,
and the library consumers, too.

I've already tried this out locally using package links, and it works great!

### CODE REVIEW

**Comment by mpashkovskiy** [comment]
Excellent! Need to read a bit about types definitions and then I will merge it.
BTW do we really need those new three packages (`@types/express`, `openapi-types` and `typescript`) as production dependencies? I thought it is needed for development time.

**Comment by sarpik** [comment]
Sure - you'll probably find this useful - https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html

As for the dependencies - I was thinking the same, but then I read this - https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies, and it looks like we do need them.

**Comment by sarpik** [comment]
Heyo, not to bother, but are there possibly any updates? I'd like to help out with other fixes / feature requests etc., but I feel like we need this first:)

**Comment by mpashkovskiy** [comment]
Hi, right, will merge it this week.

**Comment by mpashkovskiy** [comment]
@sarpik could you please confirm that everything works for you?

**Comment by mpashkovskiy** [comment]
it's pity that it doesn't work with jsdoc: https://github.com/jsdoc/jsdoc/issues/1537 or it does: https://github.com/jsdoc/jsdoc/issues/1537#issuecomment-457228326 ?

**Comment by sarpik** [comment]
@mpashkovskiy hey there.
I've updated to the latest version. Typechecking works great (with typescript / vscode) -  pretty sure that everything's fine:)

Don't know about jsdoc not working. If I open express-oas-generator's index.js file, I properly see the imported type definitions. Both the whole function definitions, their parameter names etc works.
(for example, for `handleResponses`), and everything look good (at least with vscode).

image

image

**Pull request merged**
